### ISSUE TITLE
Scroll up does not work when scrolled fully at bottom

### ISSUE THREAD

**Issue by simondavies** [lmgonzalves/spy#1]
Using Chrome 55.0.28
MacOs Sierra

Playing around with the demo using the links and scrolling normally, I noticed that when i scrolled to the very bottom I could not then use the arrow up to scroll back up.

Then i check developer console for any errors and nothing, but then tried the up arrow again and it worked, so having the console (docked) open would make it work.

Then i checked with it being slightly away from the bottom of the page (so scrolled it up slightly) and it then also worked, so the issue seems to be if the page has reached the very bottom of the page / browser.

Also tested on FF and safari and get the same issue.

Its seems that when it reaches the bottom and the down arrow is deactivated is when its not getting any click event or somethign, so scrolling up a little to activate the down arrow enables the click action of the up control.

**Comment by lmgonzalves** [comment]
Hey, thanks for reporting this. It's very strange!
However, I can see the issue only on screens with a big height.
I'll take a closer look asap :)

**Comment by lmgonzalves** [comment]
Seems to be an issue with Gumshoe. I've [reported it](https://github.com/cferdinandi/gumshoe/issues/56) :)

**Comment by lmgonzalves** [comment]
Ok, the author of the Gumshoe library say:

> That is the expected/intended behavior. Otherwise, that item would never be active.

And I think it makes sense, so I'm closing this :)

**Comment by simondavies** [comment]
not a problem, thanks for looking into it.
